In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5])
b = np.array([5,4,3,2,1])
print(a)
print(b)

[1 2 3 4 5]
[5 4 3 2 1]


In [3]:
type(a)

numpy.ndarray

In [4]:
print(a + b)
print(a - b)
print(a * a)

[6 6 6 6 6]
[-4 -2  0  2  4]
[ 1  4  9 16 25]


In [6]:
# creating 2D array
a2 = np.array([[1,2,3],[4,5,6]])
print(a2)

[[1 2 3]
 [4 5 6]]


In [9]:
# creating a 3D ARRAY
a3 = np.array([[[1,2,3],[4,5,6]],
            [[7,8,9],[10,11,12]],
            [[13,14,15],[16,17,18]]])
print(a3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


In [10]:
print(a2.shape)

(2, 3)


In [12]:
print(a3.shape)

(3, 2, 3)


In [13]:
print(a2.ndim)

2


In [14]:
print(a3.ndim)

3


In [15]:
print(a2.dtype)

int64


In [17]:
np.arange(11)
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [23]:
np.random.randint(1,11, size=(2,3))

array([[ 1,  2,  1],
       [ 4, 10,  2]], dtype=int32)

In [24]:
np.random.randint(1,11, size=(2,3,3))

array([[[10,  5,  3],
        [ 4,  1,  5],
        [ 4,  3, 10]],

       [[ 9,  9,  6],
        [ 4,  1,  3],
        [ 6,  7,  5]]], dtype=int32)

In [26]:
x = np.random.randint(1,21, size=(2,2))
y = np.random.randint(1,21, size=(2,2))
print(x)
print(y)

[[15 11]
 [ 4 16]]
[[ 7  4]
 [15  1]]


In [28]:
print(x+y)
print(x-y)
print(x*y)

[[22 15]
 [19 17]]
[[  8   7]
 [-11  15]]
[[105  44]
 [ 60  16]]


In [30]:
#matrix
#1st method
print(x @ y)

[[270  71]
 [268  32]]


In [31]:
#2nd method
np.dot(x,y)

array([[270,  71],
       [268,  32]], dtype=int32)

In [32]:
#product
x.prod()

np.int64(10560)

In [34]:
#mean
x.mean()
y.mean()

np.float64(6.75)

In [35]:
b = x.mean(axis=0)#column wise
print(b)

[ 9.5 13.5]


In [37]:
print(x)

[[15 11]
 [ 4 16]]


In [36]:
c = x.mean(axis=1) #row wise
print(c)

[13. 10.]


In [39]:
# operations
print(x.sum())
print(x.std())
print(x.var())

46
4.716990566028302
22.25


In [41]:
#np.percentile array
arr = np.array([1,2,3,4,5,6,7,8,9])
print(np.percentile(arr, 50))
print(np.percentile(arr, 25))
print(np.percentile(arr, 75))

5.0
3.0
7.0


In [43]:
arr2 = np.random.randint(11,100,(4,4))
print(arr2)

[[24 42 22 82]
 [74 80 33 48]
 [40 74 82 27]
 [96 46 94 32]]


In [44]:
#reshape method
print('2x8')
print(arr2.reshape(2,8))
print('8x2')
print(arr2.reshape(8,2))

2x8
[[24 42 22 82 74 80 33 48]
 [40 74 82 27 96 46 94 32]]
8x2
[[24 42]
 [22 82]
 [74 80]
 [33 48]
 [40 74]
 [82 27]
 [96 46]
 [94 32]]
