In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3,4,5])
b = np.array([5,4,3,2,1])
print(a)
print(b)

[1 2 3 4 5]
[5 4 3 2 1]


In [4]:
type(a)

numpy.ndarray

In [5]:
print(a + b)
print(a - b)
print(a * a)

[6 6 6 6 6]
[-4 -2  0  2  4]
[ 1  4  9 16 25]


In [6]:
# creating 2D array
a2 = np.array([[1,2,3],[4,5,6]])
print(a2)

[[1 2 3]
 [4 5 6]]


In [7]:
# creating a 3D ARRAY
a3 = np.array([[[1,2,3],[4,5,6]],
            [[7,8,9],[10,11,12]],
            [[13,14,15],[16,17,18]]])
print(a3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


In [8]:
print(a2.shape)

(2, 3)


In [9]:
print(a3.shape)

(3, 2, 3)


In [10]:
print(a2.ndim)

2


In [11]:
print(a3.ndim)

3


In [12]:
print(a2.dtype)

int64


In [13]:
np.arange(11)
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [16]:
np.random.randint(1,11, size=(2,3))

array([[1, 8, 4],
       [4, 5, 8]], dtype=int32)

In [17]:
np.random.randint(1,11, size=(2,3,3))

array([[[ 9,  9,  1],
        [10,  2,  2],
        [ 3,  9,  7]],

       [[ 3,  7,  9],
        [ 1,  8,  4],
        [ 7,  4,  9]]], dtype=int32)

In [18]:
x = np.random.randint(1,21, size=(2,2))
y = np.random.randint(1,21, size=(2,2))
print(x)
print(y)

[[ 6 17]
 [10 14]]
[[15  7]
 [13  9]]


In [19]:
print(x+y)
print(x-y)
print(x*y)

[[21 24]
 [23 23]]
[[-9 10]
 [-3  5]]
[[ 90 119]
 [130 126]]


In [20]:
#matrix
#1st method
print(x @ y)

[[311 195]
 [332 196]]


In [21]:
#2nd method
np.dot(x,y)

array([[311, 195],
       [332, 196]], dtype=int32)

In [22]:
#product
x.prod()

np.int64(14280)

In [23]:
#mean
x.mean()
y.mean()

np.float64(11.0)

In [24]:
b = x.mean(axis=0)#column wise
print(b)

[ 8.  15.5]


In [25]:
print(x)

[[ 6 17]
 [10 14]]


In [26]:
c = x.mean(axis=1) #row wise
print(c)

[11.5 12. ]


In [27]:
# operations
print(x.sum())
print(x.std())
print(x.var())

47
4.14578098794425
17.1875


In [28]:
#np.percentile array
arr = np.array([1,2,3,4,5,6,7,8,9])
print(np.percentile(arr, 50))
print(np.percentile(arr, 25))
print(np.percentile(arr, 75))

5.0
3.0
7.0


In [29]:
arr2 = np.random.randint(11,100,(4,4))
print(arr2)

[[94 94 48 75]
 [69 55 83 72]
 [12 58 78 15]
 [22 90 74 24]]


In [30]:
#reshape method
print('2x8')
print(arr2.reshape(2,8))
print('8x2')
print(arr2.reshape(8,2))

2x8
[[94 94 48 75 69 55 83 72]
 [12 58 78 15 22 90 74 24]]
8x2
[[94 94]
 [48 75]
 [69 55]
 [83 72]
 [12 58]
 [78 15]
 [22 90]
 [74 24]]


In [31]:
print(arr2)

[[94 94 48 75]
 [69 55 83 72]
 [12 58 78 15]
 [22 90 74 24]]


In [35]:
print(arr2[0]) # 0th row
print(arr2[0,1]) #0th row first column
print(arr2[-1]) #last row
print(arr2[:3]) #0th to 2nd
print(arr2[1:]) #1st to last row

[94 94 48 75]
94
[22 90 74 24]
[[94 94 48 75]
 [69 55 83 72]
 [12 58 78 15]]
[[69 55 83 72]
 [12 58 78 15]
 [22 90 74 24]]


In [36]:
arr2 > 50

array([[ True,  True, False,  True],
       [ True,  True,  True,  True],
       [False,  True,  True, False],
       [False,  True,  True, False]])

In [ ]:
y = arr2[arr2>50]
z = y.reshape(4,4)
print(z)